CREATE DATABASE TOURS

USE TOURS

CREATE TABLE USUARIOS
(
	IDUSUARIO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOMBRECOMPLETO NVARCHAR(200) NOT NULL,
	NOMBREUSUARIO NVARCHAR(200) NOT NULL,
	CORREOUSUARIO NVARCHAR(200) NOT NULL,
	CLAVEUSUARIO NVARCHAR(200) NOT NULL,
)

CREATE TABLE PAIS
(
	IDPAIS INT PRIMARY KEY IDENTITY(1,1),
	NOMBREPAIS NVARCHAR(200)
)