CREATE DATABASE TOURS

USE TOURS

CREATE TABLE USUARIOS
(
	IDUSUARIO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOMBRECOMPLETO NVARCHAR(200) NOT NULL,
	NOMBREUSUARIO NVARCHAR(200) NOT NULL,
	CORREOUSUARIO NVARCHAR(200) NOT NULL,
	CLAVEUSUARIO NVARCHAR(200) NOT NULL,
)

CREATE TABLE PAIS
(
	IDPAIS INT PRIMARY KEY IDENTITY(1,1),
	NOMBREPAIS NVARCHAR(200)
)

CREATE TABLE DESTINO
(
	IDDESTINO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(200),
	IDPAIS INT FOREIGN KEY REFERENCES PAIS(IDPAIS)
)

CREATE TABLE CATEGORIA
(
	IDCATEGORIA INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(200)
)

CREATE TABLE GUIATURISTICO
(
	IDGUIATURISTICO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(200),
	TELEFONO NVARCHAR(15),
	CORREOGUIA NVARCHAR(200) UNIQUE
)

CREATE TABLE TRANSPORTE
(
	IDTRANSPORTE INT PRIMARY KEY IDENTITY(1,1),
	TIPOTRANSPORTE NVARCHAR(200),
	CAPACIDAD INT,
)