CREATE DATABASE TOURS

USE TOURS

CREATE TABLE USUARIOS
(
	IDUSUARIO INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	NOMBRECOMPLETO NVARCHAR(200) NOT NULL,
	NOMBREUSUARIO NVARCHAR(200) NOT NULL,
	CORREOUSUARIO NVARCHAR(200) NOT NULL,
	CLAVEUSUARIO NVARCHAR(200) NOT NULL,
)

CREATE TABLE PAIS
(
	IDPAIS INT PRIMARY KEY IDENTITY(1,1),
	NOMBREPAIS NVARCHAR(200)
)

CREATE TABLE DESTINO
(
	IDDESTINO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(200),
	IDPAIS INT FOREIGN KEY REFERENCES PAIS(IDPAIS)
)

CREATE TABLE CATEGORIA
(
	IDCATEGORIA INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(200)
)

CREATE TABLE GUIATURISTICO
(
	IDGUIATURISTICO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(200),
	TELEFONO NVARCHAR(15),
	CORREOGUIA NVARCHAR(200) UNIQUE
)

CREATE TABLE TRANSPORTE
(
	IDTRANSPORTE INT PRIMARY KEY IDENTITY(1,1),
	TIPOTRANSPORTE NVARCHAR(200),
	CAPACIDAD INT,
)

CREATE TABLE CLIENTES
(
	IDCLIENTE INT PRIMARY KEY IDENTITY(1,1),
	NOMBRECOMPLETO NVARCHAR(200),
	CORREOCLIENTE NVARCHAR(200),
	TELEFONOCLIENTE NVARCHAR(15)
)

CREATE TABLE METODOPAGO
(
	IDMETODOPAGO INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(200)
)

CREATE TABLE TOURS
(
	IDTOUR INT PRIMARY KEY IDENTITY(1,1),
	NOMBRE NVARCHAR(200),
	FECHA DATE,
	HORA TIME,
	PRECIO DECIMAL(10, 2),
	IMPUESTO AS (PRECIO * 0.18) PERSISTED,
	DURACIONHORAS INT,
	FECHAHORAFIN AS DATEADD(HOUR, DURACIONHORAS, CAST (FECHA AS DATETIME) + CAST(HORA AS DATETIME)) PERSISTED,
	ESTADO AS (
        CASE 
            WHEN GETDATE() < (CAST(Fecha AS DATETIME) + CAST(Hora AS DATETIME)) 
                THEN 'VIGENTE'
            WHEN GETDATE() BETWEEN (CAST(Fecha AS DATETIME) + CAST(Hora AS DATETIME)) 
                               AND DATEADD(HOUR, DuracionHoras, CAST(Fecha AS DATETIME) + CAST(Hora AS DATETIME)) 
                THEN 'EN PROCESO'
            WHEN GETDATE() > DATEADD(HOUR, DuracionHoras, CAST(Fecha AS DATETIME) + CAST(Hora AS DATETIME)) 
                THEN 'FINALIZADO'
        END
    ),
	IDPAIS INT FOREIGN KEY REFERENCES PAIS(IDPAIS),
	IDDESTINO INT FOREIGN KEY REFERENCES DESTINO(IDDESTINO),
	IDCATEGORIA INT FOREIGN KEY REFERENCES CATEGORIA(IDCATEGORIA),
	IDGUIATURISTICO INT FOREIGN KEY REFERENCES GUIATURISTICO(IDGUIATURISTICO),
	IDTRANSPORTE INT FOREIGN KEY REFERENCES TRANSPORTE(IDTRANSPORTE),
)
CREATE TABLE RESERVAS
(
	IDRESERVA INT PRIMARY KEY IDENTITY(1,1),
	FECHARESERVA DATETIME DEFAULT GETDATE(),
	IDCLIENTE INT FOREIGN KEY REFERENCES CLIENTES(IDCLIENTE),
	IDTOUR INT FOREIGN KEY REFERENCES TOURS(IDTOUR),
	IDMETODOPAGO INT FOREIGN KEY REFERENCES METODOPAGO(IDMETODOPAGO)
)